const FEATURED_QUESTIONS_SORTING_OPTIONS = ["activity", "creation", "votes"];

const QUESTIONS_SORTING_OPTIONS = [
  ...FEATURED_QUESTIONS_SORTING_OPTIONS,
  "relevance"
];

const SORTING_ORDERS = ["desc", "asc"];

export {
  FEATURED_QUESTIONS_SORTING_OPTIONS,
  QUESTIONS_SORTING_OPTIONS,
  SORTING_ORDERS
};
